name: deploy_to_firebase_hosting

on:
  push:
    branches: [ master ]

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install modules
        run: yarn

      - name: Install ESLint
        uses: hallee/eslint-action@1.0.3
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
